### ISSUE TITLE
Data Upload with Links to an example data

### ISSUE THREAD

**Issue by alex-rind** [VALIDproject/DyNetFlowVis#104]
Allow quick demo by offering a link directly to DyNetFlowVis with preloaded data.

* Put CSV files somewhere external??

**Comment by doomsayer2** [comment]
Preloaded data will not be available or possible, as this would need to be a different state, but a download of sample data is sure possilbe.

**Comment by doomsayer2** [comment]
Done.
Just needs a short description for every dataset and right links to files so I can upload them to the server.
