### ISSUE TITLE
Adaptions on SankeyDetail and SankeyDiagram

### ISSUE THREAD

**Issue by NChristina** [VALIDproject/DyNetFlowVis#30]
-sankey diagram over time (one link with sum of all Quartals)
- different visual adaption on sankey-details

**Comment by doomsayer2** [comment]
Partially implemented though not really working atm. As we still need to decide how to visualize more nodes.

**Comment by doomsayer2** [comment]
**NEW Concept:**
- Load more button
- Overlay for each node that shows the rest of values available
![img_20170710_135621](https://user-images.githubusercontent.com/13848511/28258923-189ef832-6ad4-11e7-9075-9bcd3c8ae08d.jpg)
