### ISSUE TITLE
develop branch does not compile (on Linux)

### ISSUE THREAD

**Issue by alex-rind** [VALIDproject/DyNetFlowVis#36]
* git hash: 4a6931a
* Environment (local or deployed):  webpack 2.2.1 on a case-sensitive file system (Linux)

### Steps to reproduce

1. git clone git@github.com:VALIDproject/DyNetFlowVis.git DNFV
2. cd DNFV/
3. git checkout develop
4. npm install
5. npm start

### Observed behavior
```
ERROR in ./src/filter_data.ts
Module not found: Error: Can't resolve './filters/ParagraphFilter' in '/home/rind/scm/DNFV/src'
 @ ./src/filter_data.ts 18:0-56
 @ ./phovea.js
 @ ./phovea_registry.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./phovea_registry.js file-loader?name=buildInfo.json!/tmp/buildInfoox893sor.txt file-loader?name=phoveaMetaData.json!/tmp/metaDatalioirudi.txt ./src/index.ts

ERROR in [at-loader] src/filter_data.ts:20:29 
    TS2307: Cannot find module './filters/ParagraphFilter'.
webpack: Failed to compile.
```

### Expected behavior
* Scripts compile & test web server running

**Comment by alex-rind** [comment]
in ``filter_data.ts`` change ``import ParagraphFilter from './filters/ParagraphFilter';`` to  ``import ParagraphFilter from './filters/paragraphFilter';``

**Comment by alex-rind** [comment]
shouldn't the issue stay open until it is merged into develop?

**Comment by doomsayer2** [comment]
The issue was already fixed in my branch which is already in devlop. I had that issue too.
