### ISSUE TITLE
Ranges of EntityEuroFilter and MediaEuroFilter initally set for all data

### ISSUE THREAD

**Issue by alex-rind** [VALIDproject/DyNetFlowVis#72]
Ranges in sliders for EntityEuroFilter and MediaEuroFilter are initally span to 2100M€, which seems to be the maximum sum for all quarters, whereas the time slider is initialized to the last quarter.
Changing the time slider and then changing it back results in the value 150M€. 

Implementation hint: 
 * `sankey_diagram.ts` lines 238 & 239 set range based on `originalData`
 * `events.fire(AppConstants.EVENT_SLIDER_CHANGE, filterQuarter)` happens only by user interaction

**Comment by doomsayer2** [comment]
I know. Must be performed initially.
