### ISSUE TITLE
Make time column flexible (not only quarter)

### ISSUE THREAD

**Issue by alex-rind** [VALIDproject/DyNetFlowVis#90]
Idea: the user already prepares their CSV, so they can additionally specify the time granularity in the header of the time column (by our definition always the 3rd column). I.e. 
*  "Quarter" : 5th digit is quarter and prepended with " Q"
* "Month" : 5th & 6th digit are month e.g. "201608" and a date format could be used to display "2016 Aug"

**Comment by doomsayer2** [comment]
Is this fully working?
I changed the new time slider to the formating you provided. Is the idea still viable wih the boxes?

**Comment by alex-rind** [comment]
> Is this fully working?

No, so far we have _quarter_ and a default format, which works well for _years_.

> I changed the new time slider to the formating you provided.

A few changes need to unify these branches together (I will prepare a pull request)

>  Is the idea still viable wih the boxes?

Yes, I think it would. Here we just "decorate" the numbers provided in raw data. That could also be done in the boxes layout.

**Comment by alex-rind** [comment]
done (so far we have year, quarter, month)
