### ISSUE TITLE
Rework the sankey detail

### ISSUE THREAD

**Issue by doomsayer2** [VALIDproject/DyNetFlowVis#93]
Some things to note when sankey deatil is opend:

- Font is too big often (change font to smaller and make dependent)
- Make chart area smaller (more space for text)
- Apply the text ellipsis to the heading of the chart or the textwrap (both functions are in utitlities available)
- Make the both windows appear always in the center of the window (even if the user pressed load more 10 times and the div is now 5000px height)

**Comment by NChristina** [comment]
I start to adapt the sankey_detail view today.

**Comment by NChristina** [comment]
I already adapted following points:

- [ X] Font is too big often (change font to smaller and make dependent)
- [ X] Make chart area smaller (more space for text)
- [ ] Apply the text ellipsis to the heading of the chart or the textwrap (both functions are in utitlities available)
- [X ] Make the both windows appear always in the center of the window (even if the user pressed load more 10 times and the div is now 5000px height)
